spring:
  profiles:
    active: db, simulate
  messages:
    encoding: UTF-8

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.mallmark.litemall:  ERROR
    org.tlh.dw: info